# Предисловие {.unnumbered}

Перед Вами второе издание учебного электронного пособия «R в социологических исследованиях». Изначально оно предназначалось для магистрантов, обучающихся по направлению 39.04.01 «Социология» по программе «Цифровые методы анализа и визуализации данных», и его структура, распределение по темам, содержание и характер самостоятельных работ соответствовали дисциплине «Анализ данных в R». Между тем, пособие будет полезно не только магистрантам данной программы, но и широкому кругу лиц, занимающихся социологическими исследованиями, стремящихся расширить свой профессиональный арсенал методами обработки данных на языке R.

Первое издание по-прежнему в силе, оно доступно по [ссылке](https://domelia.github.io/R-book/). В виду того, что пакеты и сам язык довольно активно обновляются, часть кода там может работать некорректно, и приводить не к тем ожидаемым результатам, что стоит учитывать в процессе использования. 

Необходимость в обновлении пособия связана как с эволюцией и появлениием новых версий языка R (на момент написания доступна версия 4.5.2), обновлением пакетов и функций. Меняется и авторский подход к преподаванию: на смену максимальному погружению в аналитический контекст, стремлению предоставить исчерпывающую информацию о возможных версиях выполнения одной и той же задачи, существующих пакетах, расширениях и функциях, приходит понимание необходимости более глубокого закрепления материала, формирования у читателей культуры кодинга как необходимого профессионального навыка. С этой целью было создано дополнение к пособию, содержащее интерактивные обучающие материалы по каждой практической теме, предназначенные для отработки навыков использования R для решения рутинных задач, связанных с созданием переменных и более сложных структур данных, выполнением базовых трансформаций, выполнения отдельных процедур анализа.

Интерактивные задания хранятся в формате:

- [Репозитория](https://github.com/domelia/r4ssr), находящегося в открытом доступе для тех, кто хочет научиться создавать аналогичные «тьюториалы» с помощью пакета `learnr`, а может быть покритиковать и поправить автора, предложить изменения (чему она будет весьма рада).
- Одноименного пакета `r4ssr`, в который, собственно, и «упакованы» самостоятельные работы. Каждая работа развертывается в отдельный сайт с возможностью выполнения кода, получения подсказок, проверки решения. О том как пользоваться пакетом, будет сказано и показано ниже.

Цель курса, равно как и прошлого издания, состоит в том, чтобы познакомить читателей с основами языка, ключевыми командами, функциями и пакетами, которые могут быть полезными в процессе организации, сбора данных и анализа результатов социологических исследований, и особенно - в части представления и распространения результатов.

Хотя R это язык программирования, мы в ходе освоения курса мы практически не будем использовать его в этом качестве, наша основная задача - стать уверенными пользователями R и использовать его для решения профессиональных социологических и учебных задач.

Чему мы научимся:

-   Работать с различными структурами данных, импортировать и экспортировать данные в различных форматах;
-   Создавать пользовательские функции и понимать документацию к пакетам;
-   Модифицировать данные для исследовательских задач - создавать новые переменные, разъединять и соединять массивы;
-   Анализировать результаты количественных социологических исследований и проверять статистические гипотезы, как простые, так и сложные, применять многомерные методы анализа;
-   Создавать визуализации на основе результатов исследования, создавать интерактивные отчеты и простые приложения, демонстрирующие возможности R в распространении научных публикаций.

В качестве дополнительного эффекта, своего рода «экстерналией», не связанной напрямую с задачами освоения R, автор считает рассмотрение основ статистического анализа, в том числе вопросов, касающихся выдвижения, подтверждения и опровержения статистических гипотез, корректного использования методов для их проверки. 

Что по прежнему остается за кадром?

-   Мы не будем учиться создавать библиотеки и писать сложные функции;
-   Мы не сможем в полной мере охватить все методы анализа;
-   Вряд ли получится разобрать все инструменты для визуализации;
-   За пределами нашего внимания останутся и возможности R по созданию сайтов, блогов и книг.

Однако, и того, что запланировано, представляется хватит, для того, чтобы полюбить R и стать частью сообщества исследователей, использующих R в своей повседневной жизни для решения рутинных задач и поиска инновационных решений.


Автор выражает благодарность своим коллегам - преподавателям кафедры социальной и молодежной политики Института гуманитарных наук Алтайского государственного университета, участвовавшим в апробации и рецензировании материалов пособия, за ценные замечания и уточнения, моральную поддержку в ходе создания пособия. Особенные слова признательности - всем студентам, магистрантам, аспирантам, для которых это пособие стало первым шагом на пути к R. 

Работа над пособием велась параллельно с обновлением обучающего курса, что стало возможным благодаря [стипендиальной программе Фонда Владимира Потанина](https://fondpotanin.ru/activity/stipendialnaya-programma-vladimira-potanina/), предоставившего автору грант по проекту «Редизайн курса "Анализ данных в R" для магистрантов направления "Социология"».
